### ISSUE TITLE
最新版的貌似已经无法激活了，说是服务器过期

### ISSUE THREAD

**Issue by f8q8** [legend-chen/intelliJ-IDEA-License-Server#1]
最新版的貌似已经无法激活了，说是服务器过期

**Comment by legend-chen** [comment]
2019 新版本替换了泄露的RSA密钥，我这里只是提供一个最简版的服务器实现，仅供兴趣研究使用。

**Comment by f8q8** [comment]
> 2019 新版本替换了泄露的RSA密钥，我这里只是提供一个最简版的服务器实现，仅供兴趣研究使用。

非常感谢。辛苦啦~
